version: "0.2"
import:
  - "@joshuafolkken/kit/cspell/sveltekit"
ignorePaths:
  - "**/credits-config.ts"
  - "**/simon/credits.ts"
words:
  - Baer
  - Boisclair
  - COEFF
  - gameover
  - Inerney
  - mrdoob
  - mygame
  - Orbitron
  - Pixabay
  - Raycaster
  - raycaster
  - SAMEORIGIN
  - spacebar
  - threlte
  - trycloudflare
  - unstub
  - WASD
