version: "0.2"
import:
  - "@joshuafolkken/kit/cspell/sveltekit"
words:
  - threlte
  - Orbitron
  - orbitron
  - unstub
  - spacebar
  - WASD
  - gameover
  - GAMEOVER
  - Raycaster
  - raycaster
  - SAMEORIGIN
ignorePaths: []
